services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fastdockercrud
      - POSTGRES_PASSWORD=password_fdc
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  polls_pg_data:
